baseurl = "https://www.njtierney.com/"
title = "Credibly Curious"
theme = "hugo-xmin"
googleAnalytics = "UA-69408097-1"
disqus = ""
enableEmoji = true
ignoreFiles = ['\.Rmd$', '_files$', '_cache$', '\.knit\.md$', '\.utf8\.md$']
footnotereturnlinkcontents = "â†©"
pygmentsUseClasses = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "pygments"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3
[[menu.main]]
    name = "Talks"
    url = "/talks/"
    weight = 4
[[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 5
[[menu.main]]
    name = "Software"
    url = "/software/"
    weight = 6

[params]
    description = "Credibly Curious"
    GithubEdit = "https://github.com/rbind/njtierney.com/edit/master/content/"
    footer = "&copy; [Nicholas Tierney](https://njtierney.com) 2013-20 | [Github](https://github.com/njtierney) | [Twitter](https://twitter.com/nj_tierney) | [RSS](https://www.njtierney.com/post/index.xml)"

#  enable GDPR settings
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
